[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "proyecto4geeks"
version = "0.1.0"
description = "Audio detection project"
authors = [
    {name = "Alessandra"},
    {name = "Natalia"},
    {name = "Andres"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pandas>=1.5",
  "numpy>=1.25",
  "soundfile>=0.12",
  "tinytag>=1.2",
  "tqdm>=4.65",
  "datasets>=2.0"
]
[tool.setuptools]
packages = [
    "src", "app"
]
[tool.setuptools.package-dir]
"" = "."
app = "deployment/backend/app"
